Algorithm-Coding-Test-Data-Analysis/algoview

- pages/chart/index.html
- src/assets/fonts/font.css
- src/css/pages/chart.css
- src/css/style.css
- src/js/chart.js
chart page 기본 골격 마크업, 스타일, js 코드 업로드 했습니다.
> feat: chartPage 기본 구조 세팅

- src/js/chartpage.js
before: 언어 선택 시마다 데이터 받아오는 코드
after: setCharts() 함수에서 fetch 부분 밖으로 뺌
확인 부탁드립니다 :)
> refactor: chart 데이터 한 번만 받아오게 수정

- src/css/common/global.css
design: footer 페이지 하단 배치 및 간격조정
> design: footer 페이지 하단 배치 및 간격조정

- pages/chart/index.html
- src/css/pages/chart.css
디자인에 제목 부분이 있어서, h2 태그 sr-only 제거 후, 스타일 주었습니다 :)
> Chart CSS 변경 및 Chart/index.html <h2> sr-only 클래스 제거

- index.html
- src/css/pages/chart.css
- src/js/chartpage.js
+ 현재 데이터가 없는 차트에 해당하는 캔버스는 주석 처리 했습니다.
> feat: 언어에 따라 캔버스 숨김 기능

- jsconfig.json
- pages/reference/youtube/index.html
- pages/reference/youtube/style.css
feat: 컴포넌트 스크립트 코드 추가 및 절대 경로 설정
> feat: 컴포넌트 스크립트 코드 추가 및 절대 경로 설정

- dataAnalysis/notebook/get_js_dict.ipynb
- JavaScript 데이터 추출 모듈 가안 코드 수정
- 레벨 추가
> JavaScript 데이터 추출 모듈(수정) - 레벨 추가

- src/css/common/global.css
- src/css/common/header.css
- src/js/header.js
1) global.css 에 변수로 --header: 80px;  설정 후 .header-wrapper-div에  height: var(--header);로 수정
2) 헤더 이미지 절대경로로 설정
3)  position: fixed로 고정
> Header 수정했습니다.

- dataAnalysis/notebook/visualize_data/_json_to_dataframe.py
> 문제 유형 중복 처리 함수 파라미터 수정

- dataAnalysis/notebook/json_to_dataframe.ipynb
- dataAnalysis/notebook/visualize_data/_json_to_dataframe.py
메서드 및 모듈 사용하지 않은 문제들에 대해 count 값 사전처리 추가
> DataAnalysis 사전처리 추가

- index.html
- src/js/chartpage.js
새 차트가 추가될 듯하여, 캔버스 숨기는 로직 동적으로 변경합니다 :)
> refactor: 그려지지 않은 캔버스 숨기는 기능 동적으로 변경

- src/css/common/header.css
- showMenu 라는 이름의 에니메이셔 추가했습니다
> style: 햄버거 메뉴 에니메이션추가

- src/js/chartpage.js
- src/js/charts/companyChart.js
chartpage에서 정의하지 않은 함수 실행 제거
companyChart에서 if문 안에 선언된 변수가 if문 안에서 charts.push()되도록 수정
> fix: fix: chartpage 에러들 고침

- dataAnalysis/notebook/main.py
- dataAnalysis/notebook/visualize_data/get_description.py
visualization_description.txt 파일에서 차트 별 요약 추출
chart_json.data description에 병합 기능 추가
> get_description 모듈 추가

- src/css/common/sidebar.css
- src/js/common.js
- src/js/header.js
- src/js/sidebar.js
- 언어 선택 위치 변경
- 사이드바 크기 조정
- 사이드바 관련 기능 추가 및 오류 수정
> refactor: 언어 선택 위치 변경, 사이드바 크기 조정, 사이드바 관련 기능 추가 및 오류 수정

- dataAnalysis/notebook/visualize_data/_json_to_dataframe.py
> 유니코드 제거 함수 수정

- dataAnalysis/notebook/main.py
- dataAnalysis/notebook/visualize_data/__init__.py
- dataAnalysis/notebook/visualize_data/_get_description.py
get_description 모듈 수정
- unicodedata 모듈 import 추가
get_description 호출 변경
- 파일명 변경 -> \_get\_description
- \_\_init\_\_.py 
에 \_get_description 호출 추가
- main.py 의 \_get\_description import 라인 수정
> get_description 모듈 수정 및 호출 변경

- dataAnalysis/notebook/visualize_data/js_get_dict.py
get_js_dict.ipynb 파일 문제유형 파트 변경사항 js_get_dict 모듈에 동기화
> js_get_dict 모듈 문제유형 수정

- dataAnalysis/notebook/chart_data.json
- dataAnalysis/notebook/visualize_data/py_get_dict.py
- py_get_dict 모듈 수정
- chart_data.json 업데이트
> 문제유형 변경사항 업데이트

- src/js/sidebar.js
- 스크롤 이동 시 발생하는 카테고리  하이라이트 중복 현상 수정
- 수정 전
- 수정 이후
> refactor: 스크롤 이동 시 발생하는 카테고리  하이라이트 중복 현상 수정

- dataAnalysis/notebook/visualize_data/_json_to_dataframe.py
data.json 에 추가되는 check_user_func 처리 기능 추가
> _json_to_dataframe 모듈 수정

- dataAnalysis/notebook/get_js_dict.ipynb
- dataAnalysis/notebook/get_py_dict.ipynb
- dataAnalysis/notebook/visualize_data/_json_to_dataframe.py
- dataAnalysis/notebook/visualize_data/js_get_dict.py
- dataAnalysis/notebook/visualize_data/py_get_dict.py
_json_to_dataframe.py
- 모듈 및 함수 미사용 데이터 None -> FunctionNotUsed 변경
변경 사항에 영향을 받는 ipynb, py 파일 수정
> Update notebook files and modules

- dataAnalysis/notebook/chart_data.json
Function_method 컬럼의 None -> FunctionNotUsed 변경사항 적용
> Update chart_data.json (수정)
